import type { ReactNode } from 'react'
import {
  Body,
  Container,
  Head,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import { BUSINESS_NAME, colors, fontStack, LOGO_URL, SITE_URL } from '../theme'

interface EmailLayoutProps {
  /** Inbox preview line shown next to the subject. */
  preview: string
  /** Small blue tag above the heading, e.g. "APPOINTMENT REQUEST". */
  eyebrow: string
  /** Large heading, e.g. "New Appointment Request". */
  heading: string
  /** Pre-formatted Pacific-time submission timestamp. */
  submittedAt?: string
  children: ReactNode
}

/**
 * Shared shell for every notification email: navy header with the
 * PantherCreek wordmark, signal-blue accent bar, heading block, content
 * area, and footer. Layout is table-based (via react-email primitives)
 * with inline styles for broad email-client compatibility.
 */
export default function EmailLayout({
  preview,
  eyebrow,
  heading,
  submittedAt,
  children,
}: EmailLayoutProps) {
  return (
    <Html lang="en">
      <Head />
      <Preview>{preview}</Preview>
      <Body style={body}>
        <Container style={container}>
          {/* Blue brand accent bar */}
          <Section style={accentBar} />

          {/* Navy header with wordmark */}
          <Section style={header}>
            <Img
              src={LOGO_URL}
              alt={BUSINESS_NAME}
              width="220"
              style={{ margin: '0 auto' }}
            />
          </Section>

          {/* Heading block */}
          <Section style={headingBlock}>
            <Text style={eyebrowStyle}>{eyebrow}</Text>
            <Text style={headingStyle}>{heading}</Text>
            {submittedAt && <Text style={timestamp}>{submittedAt}</Text>}
          </Section>

          {/* Template-specific content */}
          <Section style={content}>{children}</Section>

          {/* Footer */}
          <Section style={footer}>
            <Text style={footerText}>
              This email was automatically generated by {BUSINESS_NAME}.
            </Text>
            <Link href={SITE_URL} style={footerLink}>
              panthercreekpt.com
            </Link>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}

const body = {
  backgroundColor: colors.page,
  fontFamily: fontStack,
  margin: 0,
  padding: '24px 12px',
}

const container = {
  backgroundColor: colors.white,
  borderRadius: '12px',
  overflow: 'hidden' as const,
  maxWidth: '600px',
  margin: '0 auto',
}

const accentBar = {
  backgroundColor: colors.signal,
  height: '5px',
  fontSize: '1px',
  lineHeight: '1px',
}

const header = {
  backgroundColor: colors.navy,
  padding: '24px',
  textAlign: 'center' as const,
}

const headingBlock = {
  padding: '30px 32px 6px',
  textAlign: 'center' as const,
}

const eyebrowStyle = {
  color: colors.signal,
  fontSize: '12px',
  fontWeight: 700,
  letterSpacing: '3px',
  textTransform: 'uppercase' as const,
  margin: '0 0 10px',
}

const headingStyle = {
  color: colors.ink,
  fontSize: '25px',
  fontWeight: 700,
  lineHeight: '1.25',
  margin: 0,
}

const timestamp = {
  color: colors.muted,
  fontSize: '13px',
  margin: '10px 0 0',
}

const content = {
  padding: '18px 32px 8px',
}

const footer = {
  borderTop: `1px solid ${colors.border}`,
  padding: '22px 32px 26px',
  textAlign: 'center' as const,
}

const footerText = {
  color: colors.muted,
  fontSize: '12px',
  lineHeight: '1.5',
  margin: '0 0 4px',
}

const footerLink = {
  color: colors.signal,
  fontSize: '12px',
  fontWeight: 700,
  textDecoration: 'none',
}
