import { createElement as h } from 'react'
import {
  Body,
  Container,
  Head,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import { BUSINESS_NAME, colors, fontStack, LOGO_URL, SITE_URL } from '../theme.js'

/**
 * Shared shell for every notification email: navy header with the
 * PantherCreek wordmark, signal-blue accent bar, heading block, content
 * area, and footer. Layout is table-based (via react-email primitives)
 * with inline styles for broad email-client compatibility.
 *
 * Written with createElement (no JSX) so Vercel's Node functions can
 * import it without a compile step.
 *
 * @param {object} props
 * @param {string} props.preview   Inbox preview line shown next to the subject.
 * @param {string} props.eyebrow   Small blue tag above the heading.
 * @param {string} props.heading   Large heading, e.g. "New Appointment Request".
 * @param {string} [props.submittedAt]  Pre-formatted Pacific-time timestamp.
 * @param {import('react').ReactNode} props.children
 */
export default function EmailLayout({ preview, eyebrow, heading, submittedAt, children }) {
  return h(Html, { lang: 'en' },
    h(Head),
    h(Preview, null, preview),
    h(Body, { style: body },
      h(Container, { style: container },
        // Blue brand accent bar
        h(Section, { style: accentBar }),

        // Navy header with wordmark
        h(Section, { style: header },
          h(Img, { src: LOGO_URL, alt: BUSINESS_NAME, width: '220', style: { margin: '0 auto' } }),
        ),

        // Heading block
        h(Section, { style: headingBlock },
          h(Text, { style: eyebrowStyle }, eyebrow),
          h(Text, { style: headingStyle }, heading),
          submittedAt ? h(Text, { style: timestamp }, submittedAt) : null,
        ),

        // Template-specific content
        h(Section, { style: content }, children),

        // Footer
        h(Section, { style: footer },
          h(Text, { style: footerText }, `This email was automatically generated by ${BUSINESS_NAME}.`),
          h(Link, { href: SITE_URL, style: footerLink }, 'panthercreekpt.com'),
        ),
      ),
    ),
  )
}

const body = {
  backgroundColor: colors.page,
  fontFamily: fontStack,
  margin: 0,
  padding: '24px 12px',
}

const container = {
  backgroundColor: colors.white,
  borderRadius: '12px',
  overflow: 'hidden',
  maxWidth: '600px',
  margin: '0 auto',
}

const accentBar = {
  backgroundColor: colors.signal,
  height: '5px',
  fontSize: '1px',
  lineHeight: '1px',
}

const header = {
  backgroundColor: colors.navy,
  padding: '24px',
  textAlign: 'center',
}

const headingBlock = {
  padding: '30px 32px 6px',
  textAlign: 'center',
}

const eyebrowStyle = {
  color: colors.signal,
  fontSize: '12px',
  fontWeight: 700,
  letterSpacing: '3px',
  textTransform: 'uppercase',
  margin: '0 0 10px',
}

const headingStyle = {
  color: colors.ink,
  fontSize: '25px',
  fontWeight: 700,
  lineHeight: '1.25',
  margin: 0,
}

const timestamp = {
  color: colors.muted,
  fontSize: '13px',
  margin: '10px 0 0',
}

const content = {
  padding: '18px 32px 8px',
}

const footer = {
  borderTop: `1px solid ${colors.border}`,
  padding: '22px 32px 26px',
  textAlign: 'center',
}

const footerText = {
  color: colors.muted,
  fontSize: '12px',
  lineHeight: '1.5',
  margin: '0 0 4px',
}

const footerLink = {
  color: colors.signal,
  fontSize: '12px',
  fontWeight: 700,
  textDecoration: 'none',
}
